# Define a imagem base
FROM python:3.9
# Define o diretório de trabalho dentro do contêiner
WORKDIR /app
# Copia o arquivo requirements.txt para o contêiner
COPY requirements.txt ./
COPY /jsons ./
COPY exampleRAG.py ./
RUN pip install --upgrade pip
# Instala as dependências especificadas no requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
# Copia o restante do código-fonte para o contêiner
COPY . .
EXPOSE 3000
# Define o comando padrão a ser executado quando o contêiner for iniciado
CMD [ "python", "./exampleRAG.py" ]